# Generated by Django 3.2.3 on 2022-04-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0002_auto_20220404_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='season',
        ),
        migrations.RemoveField(
            model_name='team',
            name='current_season',
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Liga.league'),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
