# Generated by Django 3.2.3 on 2022-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0003_auto_20220404_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='isplayed',
            field=models.BooleanField(default=False),
        ),
    ]
