# Generated by Django 3.2 on 2022-04-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0005_player_iscaptain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='iscaptain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
