# Generated by Django 3.2 on 2022-04-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Liga', '0006_auto_20220405_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='year',
            field=models.TextField(default='2022'),
        ),
    ]
